# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
